# A robust list of top active Indian stocks
# This avoids "Download Error" issues completely.

NIFTY_MASTER_LIST = [
    "RELIANCE.NS", "TCS.NS", "HDFCBANK.NS", "ICICIBANK.NS", "INFY.NS", "SBIN.NS",
    "BHARTIARTL.NS", "ITC.NS", "LICI.NS", "HINDUNILVR.NS", "LT.NS", "BAJFINANCE.NS",
    "TATAMOTORS.NS", "MARUTI.NS", "HCLTECH.NS", "SUNPHARMA.NS", "ADANIENT.NS", 
    "NTPC.NS", "TITAN.NS", "KOTAKBANK.NS", "AXISBANK.NS", "ONGC.NS", "ULTRACEMCO.NS",
    "ADANIPORTS.NS", "ASIANPAINT.NS", "WIPRO.NS", "JSWSTEEL.NS", "M&M.NS", "COALINDIA.NS",
    "VBL.NS", "ZOMATO.NS", "PAYTM.NS", "APOLLOHOSP.NS", "TATASTEEL.NS", "ABB.NS", 
    "SIEMENS.NS", "HAL.NS", "DLF.NS", "PIDILITIND.NS", "BEL.NS", "INDIGO.NS", 
    "IOC.NS", "GRASIM.NS", "POWERGRID.NS", "DMART.NS", "RECLTD.NS", "PFC.NS",
    "SBILIFE.NS", "BAJAJFINSV.NS", "BRITANNIA.NS", "GODREJCP.NS", "CHOLAFIN.NS",
    "TATACONSUM.NS", "PNB.NS", "BANKBARODA.NS", "GAIL.NS", "TRENT.NS", "HINDALCO.NS",
    "EICHERMOT.NS", "DIVISLAB.NS", "VEDL.NS", "SHREECEM.NS", "TVSMOTOR.NS", 
    "BPCL.NS", "DRREDDY.NS", "AMBUJACEM.NS", "HAVELLS.NS", "DABUR.NS", "NAUKRI.NS",
    "INDUSINDBK.NS", "JIOFIN.NS", "MOTHERSON.NS", "POLYCAB.NS", "SRF.NS", 
    "ICICIPRULI.NS", "TECHM.NS", "LTIM.NS", "HEROMOTOCO.NS", "CIPLA.NS", "MARICO.NS",
    "SBICARD.NS", "MUTHOOTFIN.NS", "BOSCHLTD.NS", "PIIND.NS", "CUMMINSIND.NS",
    "UBL.NS", "MCDOWELL-N.NS", "LUPIN.NS", "AUROPHARMA.NS", "ALKEM.NS", 
    "COLPAL.NS", "BERGEPAINT.NS", "PETRONET.NS", "IGL.NS", "INDHOTEL.NS", 
    "BHARATFORG.NS", "ASTRAL.NS", "JUBLFOOD.NS", "PAGEIND.NS", "VOLTAS.NS"
]